### ISSUE TITLE
Possible INPUT_PULLUP when not required.

### ISSUE THREAD

**Issue by NormanDunbar** [xelalexv/oqtadrive#21]
In this code:

```
// When drive is off, signal lines should be set to the least intrusive mode
// possible, to avoid interfering with any actual Microdrives that may be
// present. This is INPUT without pull-up, which for the ATmega328P has a
// typical input leakage current of 1uA.
void deactivateSignals() {
	// control signals
	pinMode(PIN_READ_WRITE, INPUT);
	pinMode(PIN_ERASE, INPUT);
	pinMode(PIN_COMMS_CLK, INPUT);
	pinMode(PIN_COMMS_IN, INPUT);
	pinMode(PIN_WR_PROTECT, INPUT);

	// tracks off
	DDRC = 0;
	PORTC = 0;
}
```

Are you aware that changing `DDRC` before `PORTC` will put some pins into `INPUT_PULLUP` mode if there are any bits set in `PORTC` when `DDRC` is written to zero? Somewhere in the bowels of the ATmega328 data sheet, it says to clear `PORTx` before configuring `DDRx` for `INPUT` pins to avoid inadvertent/temporary setting to `INPUT_PULLUP` and perhaps causing problem.

Cheers,
Norm.
(Author: Arduino Software Internals, Apress.com)

**Comment by xelalexv** [comment]
Haven't seen that before. Would swapping the two lines help?

**Comment by xelalexv** [comment]
Found it in the data sheet:

> 13.2.1 Configuring the Pin
> ...
> If PORTxn is written logic one when the pin is configured as an input pin, the pull-up resistor is activated. To switch the
pull-up resistor off, PORTxn has to be written logic zero or the pin has to be configured as an output pin. The port pins are
tri-stated when reset condition becomes active, even if no clocks are running.

So swapping the two lines in `deactivateSignals()` would fix this.

**Comment by xelalexv** [comment]
OK, maybe I should have read the next page in the data sheet as well ;-) I think this is what we're looking for. It says:

> 13.2.3 Switching Between Input and Output
> When switching between tri-state ({DDxn, PORTxn} = 0b00) and output high ({DDxn, PORTxn} = 0b11), an intermediate
state with either pull-up enabled {DDxn, PORTxn} = 0b01) or output low ({DDxn, PORTxn} = 0b10) must occur. Normally, the
pull-up enabled state is fully acceptable, as a high-impedance environment will not notice the difference between a strong
high driver and a pull-up. If this is not the case, the PUD bit in the MCUCR register can be set to disable all pull-ups in all
ports.
> Switching between input with pull-up and output low generates the same problem. The user must use either the tri-state
({DDxn, PORTxn} = 0b00) or the output high state ({DDxn, PORTxn} = 0b11) as an intermediate step.

I'm not quite sure yet about the implications, need to think about this.

**Comment by NormanDunbar** [comment]
Hi @xelalexv,

sorry about the delay in getting back to you, I've been away for a bit.

When output is HIGH, then we go from DDRC=1 + PORTC  = 1 to DDRC = 0 + PORTC = 0, and as you mention above, we can go with either:

* DDRC = 0, which, because PORTC is still = 1, would give an INPUT_PULLUP; or
* PORTC = 0, which with DDRC still =1, would give an OUTPUT LOW instead.

I have no idea about the Microdrive  hardware's response to either case. 

However, it is interesting to note in the Arduino source code for `pinMode()` that no such considerations are taken into account! What it does is as follows:

* If the mode is (now) INPUT, then DDRx bit = 0 followed by PORTx bit = 0;
* If the mode is INPUT_PULLUP, then DDRx bit = 0 followed by PORTx bit = 1;
* If the mode is OUTPUT then, DDRx bit = 1 and nothing is changed in PORTx.

I'm thinking that even the Arduino authors have not read the data sheet "properly" as the latter case could lead to a pin being set to OUTPUT while still HIGH which might not be the required action, but this depends on the application I suspect.

Cheers,
Norm.
(Author: Arduino Software Internals, Apress.com)

**Comment by xelalexv** [comment]
> I have no idea about the Microdrive hardware's response to either case.

In conclusion, I'd say (as mentioned before) that going via INPUT_PULLUP seems a clean enough way to do it. Also, considering the test mileage we've already covered with this way of switching to tri-state, I'd tend to keep it as is. Still, thanks for pointing this out! Never really thought about this before.
